"""initial schema

Revision ID: a8befdc02545
Revises: 
Create Date: 2026-07-04 03:33:05.018013

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

revision: str = 'a8befdc02545'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('app_tabs',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_app_tabs')),
    sa.UniqueConstraint('key', name=op.f('uq_app_tabs_key'))
    )
    op.create_table('permission_defs',
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('scope_type', sa.String(length=20), nullable=False),
    sa.CheckConstraint("scope_type IN ('tab','folder','global')", name=op.f('ck_permission_defs_scope_type_valid')),
    sa.PrimaryKeyConstraint('code', name=op.f('pk_permission_defs'))
    )
    op.create_table('roles',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=1000), nullable=True),
    sa.Column('is_system', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_roles')),
    sa.UniqueConstraint('name', name=op.f('uq_roles_name'))
    )
    op.create_table('users',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('password_hash', sa.String(length=255), nullable=False),
    sa.Column('full_name', sa.String(length=255), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_users')),
    sa.UniqueConstraint('email', name=op.f('uq_users_email'))
    )
    op.create_table('folders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('parent_id', sa.UUID(), nullable=True),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('materialized_path', sa.String(length=2000), nullable=False),
    sa.Column('depth', sa.Integer(), nullable=False),
    sa.Column('created_by', sa.UUID(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['created_by'], ['users.id'], name=op.f('fk_folders_created_by_users')),
    sa.ForeignKeyConstraint(['parent_id'], ['folders.id'], name=op.f('fk_folders_parent_id_folders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_folders')),
    sa.UniqueConstraint('parent_id', 'name', name='uq_folder_parent_name')
    )
    op.create_table('orders',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('uploaded_by', sa.UUID(), nullable=True),
    sa.Column('source_filename', sa.String(length=255), nullable=False),
    sa.Column('execution_date', sa.Date(), nullable=False),
    sa.Column('uploaded_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['uploaded_by'], ['users.id'], name=op.f('fk_orders_uploaded_by_users')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_orders'))
    )
    op.create_table('user_roles',
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_user_roles_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], name=op.f('fk_user_roles_user_id_users'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('user_id', 'role_id', name=op.f('pk_user_roles'))
    )
    op.create_table('event_templates',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('event_type', sa.String(length=30), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("event_type IN ('timer','weight_check','phrase_confirmation')", name=op.f('ck_event_templates_event_type_valid')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_event_templates_folder_id_folders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_event_templates'))
    )
    op.create_table('ingredients',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('measure_type', sa.String(length=20), nullable=False),
    sa.Column('description', sa.String(length=2000), nullable=True),
    sa.Column('allowed_container_weights_g', postgresql.ARRAY(sa.Integer()), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("measure_type IN ('weight','volume','time','temperature')", name=op.f('ck_ingredients_measure_type_valid')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_ingredients_folder_id_folders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ingredients'))
    )
    op.create_table('products',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('folder_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=255), nullable=False),
    sa.Column('base_quantity', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('base_quantity > 0', name=op.f('ck_products_base_quantity_positive')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_products_folder_id_folders'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_products'))
    )
    op.create_table('role_permissions',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_code', sa.String(length=50), nullable=False),
    sa.Column('tab_id', sa.UUID(), nullable=True),
    sa.Column('folder_id', sa.UUID(), nullable=True),
    sa.Column('granted', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('(tab_id IS NOT NULL AND folder_id IS NULL) OR (tab_id IS NULL AND folder_id IS NOT NULL) OR (tab_id IS NULL AND folder_id IS NULL)', name=op.f('ck_role_permissions_scope_matches_type')),
    sa.ForeignKeyConstraint(['folder_id'], ['folders.id'], name=op.f('fk_role_permissions_folder_id_folders'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['permission_code'], ['permission_defs.code'], name=op.f('fk_role_permissions_permission_code_permission_defs')),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], name=op.f('fk_role_permissions_role_id_roles'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['tab_id'], ['app_tabs.id'], name=op.f('fk_role_permissions_tab_id_app_tabs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_role_permissions')),
    sa.UniqueConstraint('role_id', 'permission_code', 'tab_id', 'folder_id', name='uq_role_perm_scope')
    )
    op.create_table('order_lines',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_id', sa.UUID(), nullable=False),
    sa.Column('row_group_index', sa.Integer(), nullable=False),
    sa.Column('product_name_raw', sa.String(length=255), nullable=False),
    sa.Column('quantity', sa.Integer(), nullable=False),
    sa.Column('due_time', sa.Time(), nullable=False),
    sa.Column('matched_product_id', sa.UUID(), nullable=True),
    sa.Column('match_status', sa.String(length=20), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("match_status IN ('matched','unmatched')", name=op.f('ck_order_lines_match_status_valid')),
    sa.CheckConstraint('quantity > 0', name=op.f('ck_order_lines_quantity_positive')),
    sa.ForeignKeyConstraint(['matched_product_id'], ['products.id'], name=op.f('fk_order_lines_matched_product_id_products')),
    sa.ForeignKeyConstraint(['order_id'], ['orders.id'], name=op.f('fk_order_lines_order_id_orders'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_order_lines'))
    )
    op.create_table('recipe_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('ingredient_id', sa.UUID(), nullable=True),
    sa.Column('quantity_canonical', sa.Integer(), nullable=True),
    sa.Column('event_template_id', sa.UUID(), nullable=True),
    sa.Column('event_params', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("(step_type = 'ingredient' AND ingredient_id IS NOT NULL AND event_template_id IS NULL AND quantity_canonical IS NOT NULL) OR (step_type = 'event' AND event_template_id IS NOT NULL AND ingredient_id IS NULL)", name=op.f('ck_recipe_steps_step_shape')),
    sa.ForeignKeyConstraint(['event_template_id'], ['event_templates.id'], name=op.f('fk_recipe_steps_event_template_id_event_templates'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['ingredient_id'], ['ingredients.id'], name=op.f('fk_recipe_steps_ingredient_id_ingredients'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_recipe_steps_product_id_products'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_recipe_steps')),
    sa.UniqueConstraint('product_id', 'order_index', name='uq_recipe_step_order')
    )
    op.create_table('execution_plans',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('order_line_id', sa.UUID(), nullable=False),
    sa.Column('product_id', sa.UUID(), nullable=False),
    sa.Column('multiplier', sa.Numeric(precision=10, scale=4), nullable=False),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('current_step_index', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint("status IN ('not_started','in_progress','completed')", name=op.f('ck_execution_plans_execution_status_valid')),
    sa.ForeignKeyConstraint(['order_line_id'], ['order_lines.id'], name=op.f('fk_execution_plans_order_line_id_order_lines'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['product_id'], ['products.id'], name=op.f('fk_execution_plans_product_id_products')),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_plans')),
    sa.UniqueConstraint('order_line_id', name=op.f('uq_execution_plans_order_line_id'))
    )
    op.create_table('execution_plan_steps',
    sa.Column('id', sa.Uuid(), nullable=False),
    sa.Column('execution_plan_id', sa.UUID(), nullable=False),
    sa.Column('order_index', sa.Integer(), nullable=False),
    sa.Column('step_type', sa.String(length=20), nullable=False),
    sa.Column('ingredient_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('measure_type_snapshot', sa.String(length=20), nullable=True),
    sa.Column('quantity_canonical_computed', sa.Integer(), nullable=True),
    sa.Column('event_name_snapshot', sa.String(length=255), nullable=True),
    sa.Column('event_type_snapshot', sa.String(length=30), nullable=True),
    sa.Column('event_params_snapshot', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('status', sa.String(length=20), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("status IN ('pending','done')", name=op.f('ck_execution_plan_steps_exec_step_status_valid')),
    sa.CheckConstraint("step_type IN ('ingredient','event')", name=op.f('ck_execution_plan_steps_exec_step_type_valid')),
    sa.ForeignKeyConstraint(['execution_plan_id'], ['execution_plans.id'], name=op.f('fk_execution_plan_steps_execution_plan_id_execution_plans'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_execution_plan_steps')),
    sa.UniqueConstraint('execution_plan_id', 'order_index', name='uq_exec_step_order')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('execution_plan_steps')
    op.drop_table('execution_plans')
    op.drop_table('recipe_steps')
    op.drop_table('order_lines')
    op.drop_table('role_permissions')
    op.drop_table('products')
    op.drop_table('ingredients')
    op.drop_table('event_templates')
    op.drop_table('user_roles')
    op.drop_table('orders')
    op.drop_table('folders')
    op.drop_table('users')
    op.drop_table('roles')
    op.drop_table('permission_defs')
    op.drop_table('app_tabs')
    # ### end Alembic commands ###
